#!/usr/bin/env bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

chunkc core::hotload 1
chunkc core::unload tiling.so
chunkc core::unload border.so

chunkc core::load border.so
chunkc core::load tiling.so

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 3_desktop_mode                monocle

chunkc set global_desktop_offset_top     4
chunkc set global_desktop_offset_bottom  4
chunkc set global_desktop_offset_left    4
chunkc set global_desktop_offset_right   4
chunkc set global_desktop_offset_gap     1

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                vertical
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            all

chunkc set mouse_follows_focus           all
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xffaf1f37
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       0

chunkc set focused_border_color          0xffc03233
chunkc set focused_border_width          5
chunkc set focused_border_radius         5
chunkc set focused_border_skip_floating  0

chunkc tiling::rule -o 'Firefox Nightly' -d 1
chunkc tiling::rule -o iTerm2 -d 2
chunkc tiling::rule -o Xcode -d 3
chunkc tiling::rule -o iTunes -d 4
chunkc tiling::rule -o '?' -d 4
