#!/usr/bin/env bash

C=~/.config
. "$C/profile"

makedirs=(
	"$HOME/.local"
	"$HOME/.cache"
)

homedot=(
	ackrc
	bash_profile
	bashrc
	editrc
	inputrc
	profile
	subversion
)

packages=(
	alacritty
	bash
	bash-completion
	coreutils
	mpv
	neovim
	newsboat
	nftables
	rsync
	sway
	swayidle
	swaylock
	sxiv
	tree
	youtube-dl
)

if [[ -z $_SERVER ]]; then
	homedot+=(
		lldbinit
		tmux.conf
	)
	packages+=(
		mpv
		youtube-dl
	)
fi

if [[ $_OS_GNU_LINUX && -z $_SERVER ]]; then
	packages+=(
		mpv
		youtube-dl
	)
fi

if [[ $_OS_MACOS ]]; then
	packages+=(
		findutils
		gnu-sed
		rename
		watch
	)

	if [[ -z $_SERVER ]]; then
		homedot+=(
			chunkwmrc
			skhdrc
		)
		packages+=(
			chunkwm
			osxfuse
			skhd
		)
	fi

	if [[ $_USE_WORK ]]; then
		packages+=(
			ios-deploy
		)
	fi
fi

# execute

echo "Making directories ${makedirs[*]}"
for dir in "${makedirs[@]}"; do
	mkdir -p "$dir"
done

link() {
	[[ "$(readlink -f "$1")" == "$(readlink -f "$2")" ]] && return
	ln -ns "$1" "$2" --backup --suffix=".old"
}

linkHome() {
	echo "Linking to home directory: $*"
	for file in "$@"; do
		link "$C/$file" "$HOME/.$file"
	done
}

private() {
	echo "Installing private data: $*"
	for path in "$@"; do
		link "$C/private/$path" "$C/$path"
	done
}

if [[ $_OS_MACOS ]]; then
	default() {
		for arg in {1..$*..2}; do
			echo ${$@[$arg]}
			defaults write "$1" ${$@[$arg]} ${$@[$arg+1]}
		done
	}
fi

if [[ $_USE_PERSONAL ]]; then
	homedot+=(
		ssh
	)

	private \
		gpg \
		mutt/public \
		newsboat/urls \
		offlineimap \
		pass \
		ssh \
		task \
		transmission-daemon
fi

linkHome "${homedot[@]}"
link "../.config/bin" "$HOME/.local/bin"

if [[ $_OS_ARCH_LINUX ]]; then
	INSTALL='sudo pacman -Syy --needed'

	if ! command -v yay &>/dev/null; then
		echo Installing yay
		git clone https://aur.archlinux.org/yay-bin.git /tmp/yay
		(cd /tmp/yay && makepkg -si)
	fi

elif [[ $_OS_MACOS ]]; then
	INSTALL='brew install'

	cp "$C"/UK.keylayout "$HOME/Library/Keyboard Layouts/UK.keylayout"

	git clone https://github.com/Shougo/dein.vim \
		"$DEIN_DIR"/repos/github.com/Shougo/dein.vim

	if ! command -v brew; then
		/usr/bin/ruby -e \
			"$(curl -fsSL \
				https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	brew ln bash
	brew tap crisidev/homebrew-chunkwm
	brew service start chunkwm skhd
	brew tap jlhonora/lsusb osxfuse/osxfuse

	brew install --HEAD ifuse ideviceinstaller
	brew install --HEAD universal-ctags/universal-ctags/universal-ctags

	screenshots="$HOME/Pictures/screens"
	mkdir -p "$screenshots"
	default com.apple.screencapture location "$screenshots"
fi

if [ -z "$INSTALL" ]; then
	>&2 echo "No installation command set for this operating system"
fi

echo "Installing: ${packages[*]}"
eval "$INSTALL" "${packages[@]}"
